# Generated by Django 5.2.17 on 2026-09-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('portion', models.CharField(default='1 porsiya', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='dishes/')),
                ('available', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category__position', 'id'],
            },
        ),
    ]
