# Generated by Django 5.2.17 on 2026-09-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='station',
            field=models.CharField(choices=[('kitchen', 'Oshxona'), ('counter', 'Kassa')], default='kitchen', max_length=10),
        ),
        migrations.AddField(
            model_name='dish',
            name='station',
            field=models.CharField(blank=True, choices=[('kitchen', 'Oshxona'), ('counter', 'Kassa')], max_length=10),
        ),
    ]
