# Generated by Django 5.2.17 on 2026-09-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_dish_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stock_kind',
            field=models.CharField(choices=[('cooked', 'Oshxona taomi'), ('goods', 'Tayyor mahsulot')], default='cooked', max_length=10),
        ),
        migrations.AddField(
            model_name='dish',
            name='stock_kind',
            field=models.CharField(blank=True, choices=[('cooked', 'Oshxona taomi'), ('goods', 'Tayyor mahsulot')], max_length=10),
        ),
    ]
