# Generated by Django 5.2.17 on 2026-09-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=80)),
                ('purpose', models.CharField(max_length=250)),
                ('recipient', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('unpaid', 'To‘lanmagan')], max_length=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('l', 'l'), ('dona', 'dona')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('minimum', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('table', models.CharField(blank=True, max_length=40)),
                ('waiter', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('paid', 'To‘langan')], default='open', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('receipt', 'Kirim'), ('consumption', 'Kunlik sarf')], max_length=12)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
