# Generated by Django 5.2.17 on 2026-09-16 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
        ('users', '0002_user_hired_at_user_notes_user_phone_user_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], max_length=10)),
                ('paid_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_salary_payments', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payment', to='operations.expense')),
            ],
            options={
                'ordering': ['-period', '-id'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'employee', 'period'), name='salary_one_payment_per_period'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='salary_payment_positive_amount')],
            },
        ),
    ]
