# Generated by Django 5.2.17 on 2026-09-18 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_order_payment_method'),
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=40)),
                ('seats', models.PositiveIntegerField(default=4)),
                ('active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='users.branch')),
            ],
            options={
                'ordering': ['number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='operations.table'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('branch', 'number'), name='table_branch_number'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='table_positive_number'),
        ),
    ]
