# Generated by Django 5.2.17 on 2026-09-18 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_order_void_reason_order_voided_at_order_voided_by_and_more'),
        ('users', '0004_auditevent_audit_branch_recent_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'date'), name='shift_one_close_per_day'), models.CheckConstraint(condition=models.Q(('counted_cash__gte', 0)), name='shift_nonnegative_count')],
            },
        ),
    ]
