# Generated by Django 5.2.17 on 2026-09-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_assistantchat_assistantmessage_and_more'),
        ('users', '0004_auditevent_audit_branch_recent_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('hall', 'Zal'), ('takeaway', 'Olib ketish'), ('uzum', 'Uzum'), ('yandex', 'Yandex')], default='hall', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waiters', to='users.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='waiter_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='operations.waiter'),
        ),
        migrations.AddConstraint(
            model_name='waiter',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='waiter_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='waiter',
            constraint=models.CheckConstraint(condition=models.Q(('commission__gte', 0), ('commission__lte', 100)), name='waiter_commission_range'),
        ),
    ]
