# Generated by Django 5.2.17 on 2026-09-19 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_station_dish_station'),
        ('operations', '0017_order_channel_order_waiter_commission_waiter_and_more'),
        ('users', '0006_admins_become_cashiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DishPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preps', to='catalog.dish')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['branch', 'date'], name='dish_prep_branch_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='dish_prep_positive')],
            },
        ),
    ]
