# Generated by Django 5.2.17 on 2026-09-19 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_remove_recipe_selling_price'),
        ('users', '0006_admins_become_cashiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'created_at'], name='order_branch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'paid_at'], name='order_branch_paid_idx'),
        ),
    ]
