# Generated by Django 5.2.17 on 2026-09-20 07:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def freeze_past_delivery_commission(apps, schema_editor):
    """Eski Uzum va Yandex buyurtmalariga standart ushlanmani yozadi.

    Platforma o'sha sotuvlarda ham o'z ulushini olgan — biz uni yozib
    bormagan edik, xolos. Nol qoldirilsa eski hisobotlar «hammasi hisobga
    tushgan» deb yolg'on ko'rsatardi.
    """
    Order = apps.get_model('operations', 'Order')
    Order.objects.filter(channel__in=['uzum', 'yandex'], channel_commission=0).update(
        channel_commission=Decimal('30'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_alter_ingredient_quantity_and_more'),
        ('users', '0006_admins_become_cashiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='ChannelFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('hall', 'Zal'), ('takeaway', 'Olib ketish'), ('uzum', 'Uzum'), ('yandex', 'Yandex')], max_length=10)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_fees', to='users.branch')),
            ],
            options={
                'ordering': ['channel'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'channel'), name='channel_fee_unique'), models.CheckConstraint(condition=models.Q(('commission__gte', 0), ('commission__lte', 100)), name='channel_fee_range')],
            },
        ),
        migrations.RunPython(freeze_past_delivery_commission, migrations.RunPython.noop),
    ]
