# Generated by Django 5.2.17 on 2026-09-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_hired_at_user_notes_user_phone_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Superadmin'), ('admin', 'Admin'), ('cashier', 'Kassir'), ('kitchen', 'Oshxona')], default='cashier', max_length=12),
        ),
    ]
