# Generated by Django 5.2.17 on 2026-09-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['branch', '-created_at', '-id'], name='audit_branch_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['branch', 'action', '-created_at'], name='audit_branch_action_idx'),
        ),
    ]
