# Generated by Django 5.2.17 on 2026-09-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auditevent_audit_branch_recent_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Superadmin'), ('cashier', 'Kassir'), ('kitchen', 'Oshxona')], default='cashier', max_length=12),
        ),
    ]
