export interface User { id: number; username: string; name: string; role: 'owner' | 'admin' | 'cashier' | 'kitchen'; branch: string }
export interface Category { id: number; name: string; position: number }
export interface Dish { id: number; category: number; category_name: string; name: string; description: string; price: string; portion: string; image: string | null; available: boolean; archived: boolean }
export interface Line { id: number; dish: number; name: string; price: string; quantity: number; note: string }
export interface Order { id: number; table: string; waiter: string; status: 'open' | 'paid'; total: string; payment_method: string; created_at: string; cashier_name: string; preparation_status: 'queued'|'preparing'|'ready'|'served'; started_at: string|null; ready_at: string|null; served_at: string|null; lines: Line[] }
export interface Expense { id: number; category: string; purpose: string; recipient: string; amount: string; payment_method: string; date: string; actor_name: string }
export interface Ingredient { id: number; name: string; unit: string; quantity: string; minimum: string }
export interface Movement { id: number; ingredient_name: string; unit: string; kind: string; quantity: string; date: string; note: string }
export interface Dashboard { revenue: string; expenses: string; net_cash: string; paid_count: number; open_count: number; previous_revenue: string; cash: string; card: string; low_stock: number; trend: {date: string; revenue: string; expenses: string}[]; expense_categories: {category: string; total: string}[]; recent_orders: Order[]; as_of: string; basis: string }
export interface SalesReport { filters:{start:string;end:string;group:'day'|'month';category:number|null;dish:number|null}; summary:{revenue:string;cost:string;gross_profit:string;gross_margin:string;orders:number;items:number;average_check:string;cash:string;card:string}; trend:{date:string;revenue:string;orders:number;items:number}[]; categories:{category_id:number;category:string;quantity:number;revenue:string;cost:string;gross_profit:string;orders:number}[]; dishes:{dish_id:number;dish:string;category:string;quantity:number;revenue:string;cost:string;gross_profit:string;orders:number}[] }
export interface RecipeLine { id:number; ingredient:number; ingredient_name:string; unit:string; quantity:string; batch_cost:string }
export interface Recipe { id:number; dish:number|null; dish_name:string; name:string; yield_quantity:string; yield_unit:string; selling_price:string; active:boolean; updated_at:string; lines:RecipeLine[]; batch_cost:string; unit_cost:string; gross_profit:string }
