# Generated by Django 5.2.17 on 2026-09-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch'),
        ),
        migrations.AddField(
            model_name='dish',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='catalog.category'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='category_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='dish_positive_price'),
        ),
    ]
