# Generated by Django 5.2.17 on 2026-09-16 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('operations', '0005_mark_existing_orders_served'),
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='orderline',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Kirim'), ('consumption', 'Kunlik sarf'), ('sale_consumption', 'Sotuv bo‘yicha sarf')], max_length=18),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('yield_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('yield_unit', models.CharField(default='porsiya', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch')),
                ('dish', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe', to='catalog.dish')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('batch_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.recipe')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='recipe_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('yield_quantity__gt', 0)), name='recipe_positive_yield'),
        ),
        migrations.AddConstraint(
            model_name='recipeline',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='recipe_ingredient_once'),
        ),
        migrations.AddConstraint(
            model_name='recipeline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='recipe_line_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='recipeline',
            constraint=models.CheckConstraint(condition=models.Q(('batch_cost__gte', 0)), name='recipe_line_nonnegative_cost'),
        ),
    ]
