# Generated by Django 5.2.17 on 2026-09-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_orderline_cost_per_unit_orderline_cost_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='orderline',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='batch_key',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
