# Generated by Django 5.2.17 on 2026-09-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_orderline_options_orderline_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd'), ('card', 'Karta'), ('uzum', 'Uzum'), ('click', 'Click'), ('yandex', 'Yandex')], max_length=10),
        ),
    ]
