# Generated by Django 5.2.17 on 2026-09-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_table_order_table_ref_table_table_branch_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['zone', 'number', 'id']},
        ),
        migrations.AddField(
            model_name='table',
            name='seating',
            field=models.CharField(choices=[('divan', 'Divan'), ('chair', 'Stulli')], default='chair', max_length=8),
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.CharField(choices=[('hall_left', 'Ichkari — chap tomon'), ('hall_right', 'Ichkari — o‘ng tomon'), ('outside', 'Tashqari')], default='hall_right', max_length=12),
        ),
    ]
