# Generated by Django 5.2.17 on 2026-09-18 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_ingredient_unit_cost_stockmovement_cost_total_and_more'),
        ('users', '0004_auditevent_audit_branch_recent_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_usage', to='operations.ingredient')),
            ],
            options={
                'ordering': ['-date', 'ingredient__name'],
                'indexes': [models.Index(fields=['branch', 'date'], name='daily_usage_branch_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'ingredient', 'date'), name='daily_usage_once_per_day'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='daily_usage_positive')],
            },
        ),
    ]
