# Generated by Django 5.2.17 on 2026-09-18 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_dailyusage'),
        ('users', '0004_auditevent_audit_branch_recent_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='void_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Ochiq'), ('paid', 'To‘langan'), ('cancelled', 'Bekor qilingan'), ('refunded', 'Qaytarilgan')], default='open', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['cancelled', 'refunded']), _negated=True), models.Q(('voided_at__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='order_void_needs_reason'),
        ),
    ]
