# Generated by Django 5.2.17 on 2026-09-18 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_shiftclose'),
        ('users', '0004_auditevent_audit_branch_recent_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='order_nonnegative_discount'),
        ),
    ]
