# Generated by Django 5.2.17 on 2026-09-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_dishprep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='selling_price',
        ),
    ]
