# Generated by Django 5.2.17 on 2026-09-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_order_order_branch_created_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='stock_nonnegative',
        ),
    ]
