# Generated by Django 5.2.17 on 2026-09-20 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_attendance_and_open_salary_payments'),
        ('users', '0007_daily_wage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], max_length=10)),
                ('paid_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('service_charge__gte', 0)), name='order_nonnegative_service'),
        ),
        migrations.AddField(
            model_name='waiterpayment',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waiter_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waiterpayment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch'),
        ),
        migrations.AddField(
            model_name='waiterpayment',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='operations.waiter'),
        ),
        migrations.AddConstraint(
            model_name='waiterpayment',
            constraint=models.UniqueConstraint(fields=('branch', 'key'), name='waiter_payment_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='waiterpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='waiter_payment_positive_amount'),
        ),
    ]
