# Generated by Django 5.2.17 on 2026-09-20 11:19

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_service_charge_and_waiter_payment'),
        ('users', '0008_branch_named_xonim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Kirim'), ('consumption', 'Kunlik sarf'), ('sale_consumption', 'Sotuv bo‘yicha sarf'), ('refund', 'Qaytarish')], max_length=18),
        ),
        migrations.AddConstraint(
            model_name='shiftclose',
            constraint=models.CheckConstraint(condition=models.Q(('difference', django.db.models.expressions.CombinedExpression(models.F('counted_cash'), '-', models.F('expected_cash')))), name='shift_difference_matches'),
        ),
    ]
