# Generated by Django 5.2.17 on 2026-09-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_refund_kind_and_shift_check'),
        ('users', '0008_branch_named_xonim'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=10)),
                ('kind', models.CharField(max_length=12)),
                ('payload', models.BinaryField()),
                ('status', models.CharField(choices=[('queued', 'Navbatda'), ('printing', 'Agent oldi'), ('done', 'Chiqdi'), ('failed', 'Chiqmadi')], default='queued', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('agent', models.CharField(blank=True, max_length=60)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='users.branch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='operations.order')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['branch', 'status', 'station'], name='print_queue_idx')],
            },
        ),
    ]
