# Generated by Django 5.2.17 on 2026-09-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_print_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd'), ('card', 'Karta'), ('terminal', 'Terminal'), ('uzum', 'Uzum'), ('click', 'Click'), ('yandex', 'Yandex')], max_length=10),
        ),
    ]
