# Generated by Django 5.2.17 on 2026-09-22 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_stock_kind'),
        ('operations', '0028_terminal_payment_method'),
        ('users', '0008_branch_named_xonim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dishprep',
            name='dish_prep_positive',
        ),
        migrations.AlterField(
            model_name='dishprep',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='dishprep',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='dish_prep_not_zero'),
        ),
    ]
