# Generated by Django 5.2.17 on 2026-09-22 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_stock_kind'),
        ('operations', '0031_attendance_and_salary_follow_the_employee'),
        ('users', '0009_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Kirim'), ('consumption', 'Kunlik sarf'), ('sale_consumption', 'Sotuv bo‘yicha sarf'), ('refund', 'Qaytarish'), ('partner_sale', 'Hamkorga jo‘natildi')], max_length=18),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('school', 'Maktab'), ('university', 'Universitet'), ('office', 'Ofis'), ('other', 'Boshqa')], default='school', max_length=12)),
                ('contact', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='users.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('sent', 'Jo‘natildi'), ('reported', 'Hisobot berildi'), ('settled', 'Yopildi'), ('cancelled', 'Bekor qilingan')], default='sent', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('due_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('settled_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_deliveries', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_deliveries', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='operations.partner')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('menu_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='operations.partnerdelivery')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.dish')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_prices', to='catalog.dish')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='operations.partner')),
            ],
            options={
                'ordering': ['dish__name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('terminal', 'Terminal'), ('click', 'Click')], max_length=10)),
                ('paid_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_settlements', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='operations.partnerdelivery')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='operations.partner')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='partner_branch_name'),
        ),
        migrations.AddIndex(
            model_name='partnerdelivery',
            index=models.Index(fields=['branch', 'date'], name='partner_delivery_date_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerdelivery',
            index=models.Index(fields=['branch', 'status', 'date'], name='partner_delivery_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnerdelivery',
            constraint=models.UniqueConstraint(fields=('branch', 'key'), name='partner_delivery_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='partnerdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='partner_delivery_positive_total'),
        ),
        migrations.AddConstraint(
            model_name='partnerdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('cost_total__gte', 0), ('due_total__gte', 0), ('settled_total__gte', 0)), name='partner_delivery_nonnegative_money'),
        ),
        migrations.AddConstraint(
            model_name='partnerdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'sent'), _negated=True), ('due_total', 0), _connector='OR'), name='partner_delivery_sent_owes_nothing'),
        ),
        migrations.AddConstraint(
            model_name='partnerdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'settled'), _negated=True), ('settled_total__gte', models.F('due_total')), _connector='OR'), name='partner_delivery_settled_is_paid'),
        ),
        migrations.AddConstraint(
            model_name='partnerdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['reported', 'settled']), _negated=True), ('reported_at__isnull', False), _connector='OR'), name='partner_delivery_report_has_time'),
        ),
        migrations.AddConstraint(
            model_name='partnerdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancelled_at__isnull', False), models.Q(('cancel_reason', ''), _negated=True)), _connector='OR'), name='partner_delivery_cancel_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='partnerdeliveryline',
            constraint=models.UniqueConstraint(fields=('delivery', 'dish'), name='partner_line_dish_once'),
        ),
        migrations.AddConstraint(
            model_name='partnerdeliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='partner_line_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='partnerdeliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='partner_line_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='partnerdeliveryline',
            constraint=models.CheckConstraint(condition=models.Q(('sold_quantity__lte', models.F('quantity'))), name='partner_line_sold_fits'),
        ),
        migrations.AddConstraint(
            model_name='partnerprice',
            constraint=models.UniqueConstraint(fields=('partner', 'dish'), name='partner_price_once'),
        ),
        migrations.AddConstraint(
            model_name='partnerprice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='partner_price_positive'),
        ),
        migrations.AddIndex(
            model_name='partnersettlement',
            index=models.Index(fields=['branch', 'paid_on'], name='partner_settlement_paid_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnersettlement',
            constraint=models.UniqueConstraint(fields=('branch', 'key'), name='partner_settlement_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='partnersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='partner_settlement_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='partnersettlement',
            constraint=models.CheckConstraint(condition=models.Q(('voided_at__isnull', True), models.Q(('void_reason', ''), _negated=True), _connector='OR'), name='partner_settlement_void_needs_reason'),
        ),
    ]
