# Generated by Django 5.2.17 on 2026-09-22 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_price_into_menu_price(apps, schema_editor):
    """Eski qatorlarda menyu narxi = sotilgan narx.

    Ustun ikki xil ma'noni anglatmasligi kerak: yangi qatorlarda u sotuv
    paytidagi menyu narxi, eskilarida esa nol bo'lib qolsa, «qanchalik pul
    bonusga ketdi» hisobi jim turib noto'g'ri chiqardi.
    """
    OrderLine = apps.get_model('operations', 'OrderLine')
    OrderLine.objects.update(menu_price=models.F('price'))


def leave_menu_price_alone(apps, schema_editor):
    """Orqaga qaytishda hech narsa qilmaydi: ustunning o'zi olib tashlanadi."""


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_stock_kind'),
        ('operations', '0032_partners'),
        ('users', '0009_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderline',
            name='menu_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('receipt', 'Kirim'), ('consumption', 'Kunlik sarf'), ('sale_consumption', 'Sotuv bo‘yicha sarf'), ('refund', 'Qaytarish'), ('partner_sale', 'Hamkorga jo‘natildi'), ('staff_meal', 'Hodimlar ovqati')], max_length=18),
        ),
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('hall', 'Zal'), ('takeaway', 'Olib ketish'), ('uzum', 'Uzum'), ('yandex', 'Yandex')], max_length=10)),
                ('free_quantity', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonus_rules', to='users.branch')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonus_rules', to='catalog.dish')),
            ],
            options={
                'ordering': ['channel', 'dish__name'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'channel', 'dish'), name='bonus_rule_unique'), models.CheckConstraint(condition=models.Q(('free_quantity__gt', 0)), name='bonus_rule_positive')],
            },
        ),
        migrations.CreateModel(
            name='StaffMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('menu_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.branch')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_meals', to='catalog.dish')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'date'], name='staff_meal_branch_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'key'), name='staff_meal_idempotency'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='staff_meal_positive')],
            },
        ),
        migrations.RunPython(copy_price_into_menu_price, leave_menu_price_alone),
    ]
