# Generated by Django 5.2.17 on 2026-09-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_bonus_and_staff_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
