# Generated by Django 5.2.17 on 2026-09-24 15:52

import django.db.models.deletion
from django.db import migrations, models


def fill_in_the_payments_that_already_happened(apps, schema_editor):
    """Har bir to'langan hisobga bitta to'lov qatori yozadi.

    Eski hisobda bo'linish bo'lishi mumkin emas edi, shuning uchun butun
    summa o'sha bitta usulga tegishli. `sales` va `service` ham o'sha
    hisobning o'z maydonlaridan olinadi, ya'ni hech bir yig'indi
    o'zgarmaydi.

    Qaytarilgan hisoblar ham kiritiladi: pul haqiqatda kelgan va keyin
    qaytarilgan — bu ikki alohida voqea. Hisobotlar baribir hisob
    holatiga qarab filtrlaydi.
    """
    Order = apps.get_model('operations', 'Order')
    OrderPayment = apps.get_model('operations', 'OrderPayment')
    rows = []
    known = Order.objects.filter(status__in=['paid', 'refunded']).exclude(payment_method='')
    for order in known.iterator(chunk_size=500):
        amount = order.total + order.service_charge
        if amount <= 0:
            # Nol summali hisobga to'lov qatori yozilmaydi: cheklov uni
            # rad etadi va uning ma'nosi ham yo'q.
            continue
        rows.append(OrderPayment(
            order=order, method=order.payment_method,
            amount=amount, sales=order.total, service=order.service_charge,
        ))
        if len(rows) >= 500:
            OrderPayment.objects.bulk_create(rows)
            rows = []
    if rows:
        OrderPayment.objects.bulk_create(rows)


def drop_the_payment_rows(apps, schema_editor):
    """Orqaga qaytishda qatorlar jadval bilan birga ketadi."""


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0034_ingredient_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('terminal', 'Terminal'), ('uzum', 'Uzum'), ('click', 'Click'), ('yandex', 'Yandex')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('service', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='operations.order')),
            ],
            options={
                'ordering': ['-amount', 'id'],
                'indexes': [models.Index(fields=['order'], name='order_payment_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'method'), name='order_payment_one_row_per_method'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='order_payment_positive')],
            },
        ),
        migrations.RunPython(fill_in_the_payments_that_already_happened, drop_the_payment_rows),
    ]
