<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowRight, ShieldCheck, UtensilsCrossed } from '@lucide/vue'
import { api, refreshCsrf, session } from '../api'
import type { User } from '../types'
const router = useRouter(), username = ref('owner'), password = ref(''), busy = ref(false), error = ref('')
async function login() { busy.value = true; error.value = ''; try { await refreshCsrf(); session.user = await api<User>('auth/login/', {method:'POST',body:JSON.stringify({username:username.value,password:password.value})}); await refreshCsrf(); session.ready = true; await router.push(session.user.role === 'owner' ? '/' : session.user.role === 'kitchen' ? '/kitchen' : '/pos') } catch(e) { error.value = (e as Error).message } finally { busy.value = false } }
</script>
<template><div class="login-page"><section class="login-story"><div class="brand light"><span class="brand-mark">h<span>•</span></span><span class="brand-text">honim<span>RESTAURANT WORKSPACE</span></span></div><div class="login-headline"><span class="eyebrow">MEHMONDO‘STLIK. TARTIB. NAZORAT.</span><h1>Restoraningiz.<br>Bir butun<br><em>ish maydoni.</em></h1><p>Buyurtmadan kun yakunigacha — har bir tafsilot o‘z o‘rnida.</p><div class="login-orbit"><div><UtensilsCrossed :size="60" :stroke-width="1"/></div></div></div><small>Honim · Restoran boshqaruv tizimi</small></section><section class="login-form"><span class="pill">Xush kelibsiz</span><h2>Ish kunini boshlaymiz.</h2><p class="muted">Hisobingizga kirib, restoranni boshqaring.</p><form @submit.prevent="login"><label>Login<input v-model="username" autocomplete="username" required placeholder="Loginingiz"></label><label>Parol<input v-model="password" type="password" autocomplete="current-password" required placeholder="Parolingizni kiriting"></label><p v-if="error" class="alert error" role="alert">{{ error }}</p><button class="button primary" :disabled="busy">{{ busy ? 'Tekshirilmoqda…' : 'Tizimga kirish' }}<ArrowRight :size="18"/></button></form><p class="security-note"><ShieldCheck :size="18"/>Himoyalangan sessiya orqali kirish</p><div class="login-help">Mahalliy sinov hisobi uchun login va parol loyiha ichidagi <strong>.local-access.txt</strong> faylida.</div><RouterLink to="/menu" class="text-link">Mijoz menyusini ko‘rish →</RouterLink></section></div></template>
