<script setup lang="ts">
import { onMounted, ref } from 'vue'
import QRCode from 'qrcode'
import { QrCode, ExternalLink, ShieldCheck, Server, CheckCircle2, Clock3 } from '@lucide/vue'
import { api, dateLabel, session } from '../api'
const qr=ref(''), error=ref(''), url=`${window.location.origin}/menu`, audit=ref<{id:number;action:string;description:string;created_at:string;actor__username:string}[]>([])
onMounted(async()=>{try{qr.value=await QRCode.toDataURL(url,{width:260,margin:2,color:{dark:'#153d32',light:'#ffffff'}});if(session.user?.role==='owner')audit.value=await api('audit/')}catch(e){error.value=(e as Error).message}})
</script>
<template><div class="page-heading"><div><span class="eyebrow">ISH MAYDONI</span><h1>Sozlamalar va QR<span class="heading-dot">.</span></h1><p>Mahalliy versiya, menyu havolasi va nazorat tarixi.</p></div></div><p v-if="error" class="alert error">{{ error }}</p><div class="settings-grid"><section class="panel qr-panel"><QrCode :size="26"/><h2>Mijoz menyusi</h2><p class="muted">Faqat menyu ko‘rish uchun</p><img v-if="qr" :src="qr" alt="Mijoz menyusi QR kodi" width="230" height="230"><code>{{ url }}</code><RouterLink to="/menu" target="_blank" class="button primary">Menyuni ochish <ExternalLink :size="16"/></RouterLink><p class="data-note">Bu QR localhost manziliga olib boradi. Telefonlardan foydalanish uchun LAN yoki ommaviy domen bilan sozlash kerak.</p></section><section class="panel version-panel"><span class="pill">0.1 · Mahalliy ishlab chiqish</span><h2>Ishlaydigan asos</h2><p class="muted">Haqiqiy yozuvlar saqlanadi. To‘liq restoran tizimi bosqichma-bosqich quriladi.</p><ul class="feature-list"><li><CheckCircle2/>Sessiya, CSRF va rol bo‘yicha ruxsat</li><li><CheckCircle2/>Kategoriya, taom va rasm yuklash</li><li><CheckCircle2/>Buyurtma, to‘lov qaydi va brauzer cheki</li><li><CheckCircle2/>Xarajatlar va tushum grafigi</li><li><CheckCircle2/>Ombor kirimi va haqiqiy sarf</li><li><CheckCircle2/>Xodim profili, oylik va to‘lovlar tarixi</li><li class="pending"><Clock3/>Retsept, tannarx va smenalar</li><li class="pending"><Clock3/>Printer/fiskal va bulut sinxronlash</li></ul><div class="inline-tip"><Server :size="20"/>Mahalliy SQLite · production uchun PostgreSQL</div><div class="inline-tip"><ShieldCheck :size="20"/>Faqat localhost uchun ishga tushirilgan</div></section></div><section v-if="session.user?.role==='owner'" class="panel spaced"><header class="panel-heading"><div><h2>Amallar tarixi</h2><p>So‘nggi 100 ta qayd · faqat superadmin</p></div></header><div class="table-wrap"><table><thead><tr><th>VAQT</th><th>XODIM</th><th>AMAL</th><th>TAFSILOT</th></tr></thead><tbody><tr v-for="a in audit" :key="a.id"><td>{{ dateLabel(a.created_at) }}</td><td>{{ a.actor__username }}</td><td>{{ a.action }}</td><td>{{ a.description }}</td></tr></tbody></table><p v-if="!audit.length" class="empty-state compact">Hali amallar qayd etilmagan.</p></div></section></template>
